networks:
  monitor:


services:

  node-exporter:
    image: prom/node-exporter:v1.2.2
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - monitor

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: microblog
      MYSQL_USER: microblog
      MYSQL_PASSWORD: microblogpass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  prod:
    build:
      context: .
      dockerfile: docker/Dockerfile_prod
    container_name: microblog
    restart: always
    environment:
      FLASK_APP: microblog
      FLASK_ENV: production
      DATABASE_URL: mysql+pymysql://microblog:microblogpass@db/microblog
    depends_on:
      - db
    ports:
      - "5000:5000"

  test:
    build:
      context: .
      dockerfile: docker/Dockerfile_test
    container_name: microblog_test
    environment:
      FLASK_ENV: testing
      DATABASE_URL: mysql+pymysql://microblog:microblogpass@db/microblog_test
    depends_on:
      - db
    volumes:
      - ./:/app
    command: ["/run-tests.sh"]

volumes:
  db_data:
