global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: node-exporter
  - job_name: "prometheus"
    static_configs:
      - targets: ['0.0.0.0:9090']
        labels:
          instance: prometheus
  - job_name: "flask"
    static_configs:
      - targets: ['devops-prod-1:5000']
        labels:
          instance: flask
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'

rule_files:
  - rules.yml