---
# Here you can add variables that will be available for all hosts.
ansible_python_interpreter: "python3"

region: northeurope
resource_group: DIDA-WISE23-DV1673-H25-LP2
domain_name: vemvadetsomkasta.tech

admin_email: wise23@student.bth.se

vmtags:
    StudentId: wise23


pub_ssh_key_location: '/home/stonie/.ssh/azure.pub'


server_user: "deploy"
server_user_pass: "WiseSang123!"
server_user_groups:
    -   sudo