---
# Here you can add variables that will be available for all hosts.
ansible_python_interpreter: "python3"

region: northeurope
resource_group: DIDA-SANG22-DV1673-H25-LP2
domain_name: dusktilldawn.me

admin_email: sang22@student.bth.se

vmtags:
    StudentId: sang22


pub_ssh_key_location: '/home/sandy/.ssh/azure.pub'


server_user: "deploy"
server_user_pass: "WiseSang123!"
server_user_groups:
    -   sudo
