# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Security test

on:
  workflow_call:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Makefile
      run: |
        make install-test

    - name: Run bandit
      run: |
        make test-bandit

    - name: Run trivy
      run: |
        make scan-all

    - name: Run dockle
      run: |
        make scan-docker
